on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      recipes:
        description: "Which recipes to build, takes precedent"
      all:
        description: "Build all recipes"
        type: boolean
        default: false

permissions:
  contents: read

name: Cook recipes

jobs:
  cook:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} build

    env:
      CC: clang
      CXX: clang++
      OBJC: clang
      OBJCXX: clang++

    strategy:
      matrix:
        os: [ macos-13, macos-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # default is 1
          ref: "${{ github.ref }}"

      - name: build libs
        shell: bash
        run: ./build.sh ${{ inputs.recipes }}

      - name: Collect
        if: success() && (inputs.recipes || steps.find.outputs.recipes)
        run: mkdir deploy && cp -p build/*-darwin*.tar.gz deploy/

      - name: Upload
        if: success() && (inputs.recipes || steps.find.outputs.recipes)
        uses: actions/upload-artifact@master
        with:
          name: recipes-build
          path: deploy
